### ISSUE TITLE
Feature request: Grid usable as coverage layer for the atlas

### ISSUE THREAD

**Issue by ktrinko** [ioalexei/modular_grid_builder#7]
Dear sir!

It would be nice, if the grid could be used as the coverage layer for the atlas

**Comment by ioalexei** [comment]
Hi @ktrinko - because this grid is just made up of page measurements it doesn't have any spatial reference information like the grids generated by the vector tools do, so I don't think it could be used for a coverage layer?

But I do need to test out how to get it to work well with Atlases in general, I'll create a separate issue for that.
